// Pinned metadata only: FX 98a95f7; blocks 6a74c95. No rendering code.
export const fxData = [
  {
    id: 'effect.flash',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'speed',
        label: 'Speed',
        type: 'number',
        min: 0.1,
        max: 5,
        default: 1,
      },
      {
        name: 'loop',
        label: 'Loop',
        type: 'boolean',
        min: 0,
        max: 1,
        default: false,
      },
    ],
  },
  {
    id: 'effect.pulse',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'speed',
        label: 'Speed',
        type: 'number',
        min: 0.1,
        max: 5,
        default: 1,
      },
    ],
  },
  {
    id: 'effect.spin',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'speed',
        label: 'Speed',
        type: 'number',
        min: 0.1,
        max: 5,
        default: 1,
      },
      {
        name: 'loop',
        label: 'Loop',
        type: 'boolean',
        min: 0,
        max: 1,
        default: false,
      },
    ],
  },
  {
    id: 'effect.rotate',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'angle',
        label: 'Angle',
        type: 'number',
        min: -180,
        max: 180,
        default: 15,
      },
    ],
  },
  {
    id: 'effect.crash-zoom',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'speed',
        label: 'Speed',
        type: 'number',
        min: 0.1,
        max: 5,
        default: 1,
      },
      {
        name: 'loop',
        label: 'Loop',
        type: 'boolean',
        min: 0,
        max: 1,
        default: false,
      },
    ],
  },
  {
    id: 'effect.slow-zoom',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'speed',
        label: 'Speed',
        type: 'number',
        min: 0.1,
        max: 5,
        default: 1,
      },
      {
        name: 'loop',
        label: 'Loop',
        type: 'boolean',
        min: 0,
        max: 1,
        default: false,
      },
    ],
  },
  {
    id: 'effect.slow-zoom-random',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'speed',
        label: 'Speed',
        type: 'number',
        min: 0.1,
        max: 5,
        default: 1,
      },
      {
        name: 'loop',
        label: 'Loop',
        type: 'boolean',
        min: 0,
        max: 1,
        default: false,
      },
    ],
  },
  {
    id: 'effect.blur',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'radius',
        label: 'Radius (at 720px height)',
        type: 'number',
        min: 0,
        max: 32,
        default: 6,
      },
    ],
  },
  {
    id: 'effect.blur-fill',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'radius',
        label: 'Background blur',
        type: 'number',
        min: 1,
        max: 32,
        default: 16,
      },
      {
        name: 'scale',
        label: 'Foreground scale',
        type: 'number',
        min: 0.25,
        max: 1,
        default: 0.72,
      },
    ],
  },
  {
    id: 'effect.vhs',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'speed',
        label: 'Speed',
        type: 'number',
        min: 0.1,
        max: 5,
        default: 1,
      },
      {
        name: 'noise',
        label: 'Noise',
        type: 'number',
        min: 0,
        max: 50,
        default: 12,
      },
    ],
  },
  {
    id: 'effect.vaporwave',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'speed',
        label: 'Speed',
        type: 'number',
        min: 0.1,
        max: 5,
        default: 1,
      },
      {
        name: 'noise',
        label: 'Noise',
        type: 'number',
        min: 0,
        max: 50,
        default: 6,
      },
    ],
  },
  {
    id: 'effect.chromatic-aberration',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'amount',
        label: 'Channel offset',
        type: 'number',
        min: 0,
        max: 40,
        default: 8,
      },
    ],
  },
  {
    id: 'effect.glitch',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'speed',
        label: 'Speed',
        type: 'number',
        min: 0.1,
        max: 5,
        default: 1,
      },
    ],
  },
  {
    id: 'effect.filmic',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'speed',
        label: 'Speed',
        type: 'number',
        min: 0.1,
        max: 5,
        default: 1,
      },
      {
        name: 'grain',
        label: 'Grain',
        type: 'number',
        min: 0,
        max: 40,
        default: 14,
      },
    ],
  },
  {
    id: 'effect.color-shift',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'speed',
        label: 'Speed',
        type: 'number',
        min: 0.1,
        max: 5,
        default: 1,
      },
    ],
  },
  {
    id: 'effect.pixelation',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'size',
        label: 'Block size (at 720px height)',
        type: 'number',
        min: 1,
        max: 80,
        default: 18,
      },
      {
        name: 'palette16',
        label: '16-bit RGB565 palette',
        type: 'boolean',
        min: 0,
        max: 1,
        default: false,
      },
    ],
  },
  {
    id: 'effect.glow',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'radius',
        label: 'Radius (at 720px height)',
        type: 'number',
        min: 0,
        max: 32,
        default: 6,
      },
    ],
  },
  {
    id: 'effect.diffusion',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'radius',
        label: 'Radius (at 720px height)',
        type: 'number',
        min: 0,
        max: 32,
        default: 6,
      },
    ],
  },
  {
    id: 'effect.disco',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'speed',
        label: 'Speed',
        type: 'number',
        min: 0.1,
        max: 5,
        default: 1,
      },
    ],
  },
  {
    id: 'effect.glass',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'speed',
        label: 'Speed',
        type: 'number',
        min: 0.1,
        max: 5,
        default: 1,
      },
      {
        name: 'size',
        label: 'Glass cell size',
        type: 'number',
        min: 8,
        max: 160,
        default: 48,
      },
      {
        name: 'amount',
        label: 'Refraction',
        type: 'number',
        min: 0,
        max: 30,
        default: 8,
      },
    ],
  },
  {
    id: 'effect.comic',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'levels',
        label: 'Colour levels',
        type: 'number',
        min: 2,
        max: 12,
        default: 5,
      },
      {
        name: 'edge',
        label: 'Ink threshold',
        type: 'number',
        min: 10,
        max: 200,
        default: 65,
      },
    ],
  },
  {
    id: 'effect.retro-graphics',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'size',
        label: 'Halftone cell',
        type: 'number',
        min: 3,
        max: 40,
        default: 8,
      },
    ],
  },
  {
    id: 'effect.vertical',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'speed',
        label: 'Speed',
        type: 'number',
        min: 0.1,
        max: 5,
        default: 1,
      },
      {
        name: 'amount',
        label: 'Vertical wave',
        type: 'number',
        min: 0,
        max: 0.3,
        default: 0.08,
      },
    ],
  },
  {
    id: 'effect.radial',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'amount',
        label: 'Radial streak',
        type: 'number',
        min: 0,
        max: 0.4,
        default: 0.12,
      },
    ],
  },
  {
    id: 'effect.smoke',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'speed',
        label: 'Speed',
        type: 'number',
        min: 0.1,
        max: 5,
        default: 1,
      },
    ],
  },
  {
    id: 'effect.kaleidoscope',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'segments',
        label: 'Segments',
        type: 'number',
        min: 2,
        max: 24,
        default: 6,
      },
    ],
  },
  {
    id: 'effect.black-white-removal',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'color',
        label: 'Remove',
        type: 'select',
        min: 0,
        max: 1,
        default: 'black',
        options: ['black', 'white'],
      },
      {
        name: 'threshold',
        label: 'Threshold',
        type: 'number',
        min: 0,
        max: 0.8,
        default: 0.1,
      },
      {
        name: 'softness',
        label: 'Soft edge',
        type: 'number',
        min: 0.001,
        max: 0.5,
        default: 0.1,
      },
    ],
  },
  {
    id: 'effect.green-screen',
    kind: 'effect',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'screen',
        label: 'Screen colour',
        type: 'color',
        min: 0,
        max: 16777215,
        default: '#00ff00',
      },
      {
        name: 'threshold',
        label: 'Threshold',
        type: 'number',
        min: 0,
        max: 0.8,
        default: 0.2,
      },
      {
        name: 'softness',
        label: 'Soft edge',
        type: 'number',
        min: 0.001,
        max: 0.5,
        default: 0.1,
      },
    ],
  },
  {
    id: 'filter.none',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.retro',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.orange-teal',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.bold-blue',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.golden-hour',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.vibrant-vlogger',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.purple-undertone',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.winter-sunset',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.35mm',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.contrast',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.fall',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.winter',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.old-western',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.warm-coastline',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.cool-coastline',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.warm-countryside',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.cool-countryside',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.golden',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.dreamscape',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.sunrise',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.warm-tone',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.cool-tone',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.pastel-dreams',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.scenery',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.portrait',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.indoors',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.outdoors',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.muted',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.black-white',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.soft-bw',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.muted-bw',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.gloomy',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.deep-fried',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.euphoric',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.duotone-yellow-orange',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.duotone-pink-purple',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.duotone-blue-pink',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.duotone-green-blue',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.overlay-white',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.overlay-black',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.overlay-yellow',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.overlay-orange',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.overlay-red',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.overlay-pink',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.overlay-purple',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.overlay-blue',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'filter.overlay-green',
    kind: 'filter',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
    ],
  },
  {
    id: 'adjust.exposure',
    kind: 'adjustment',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'amount',
        label: 'Amount',
        type: 'number',
        min: -1,
        max: 1,
        default: 0,
      },
    ],
  },
  {
    id: 'adjust.contrast',
    kind: 'adjustment',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'amount',
        label: 'Amount',
        type: 'number',
        min: -1,
        max: 1,
        default: 0,
      },
    ],
  },
  {
    id: 'adjust.saturation',
    kind: 'adjustment',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'amount',
        label: 'Amount',
        type: 'number',
        min: -1,
        max: 1,
        default: 0,
      },
    ],
  },
  {
    id: 'adjust.temperature',
    kind: 'adjustment',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'amount',
        label: 'Amount',
        type: 'number',
        min: -1,
        max: 1,
        default: 0,
      },
    ],
  },
  {
    id: 'adjust.transparency',
    kind: 'adjustment',
    params: [
      {
        name: 'intensity',
        label: 'Intensity',
        type: 'number',
        min: 0,
        max: 1,
        default: 1,
      },
      {
        name: 'amount',
        label: 'Amount',
        type: 'number',
        min: -1,
        max: 1,
        default: 0,
      },
    ],
  },
] as const;
export const blockData = [
  {
    id: 'counter',
    version: '1.0.0',
    params: [
      {
        name: 'from',
        label: 'From',
        type: 'number',
        min: -1000000,
        max: 1000000,
        step: 1,
        default: 0,
      },
      {
        name: 'to',
        label: 'To',
        type: 'number',
        min: -1000000,
        max: 1000000,
        step: 1,
        default: 1200,
      },
      {
        name: 'seconds',
        label: 'Count duration',
        type: 'number',
        min: 0.1,
        max: 20,
        step: 0.1,
        default: 3,
      },
      {
        name: 'easing',
        label: 'Easing',
        type: 'select',
        options: ['linear', 'ease-in', 'ease-out', 'ease-in-out', 'hold'],
        default: 'ease-out',
      },
      {
        name: 'prefix',
        label: 'Prefix',
        type: 'text',
        default: '',
        maxLength: 100,
      },
      {
        name: 'suffix',
        label: 'Suffix',
        type: 'text',
        default: ' projects',
        maxLength: 100,
      },
      {
        name: 'color',
        label: 'Accent',
        type: 'color',
        default: '#64e3c3',
      },
      {
        name: 'glow',
        label: 'Glow',
        type: 'bool',
        default: true,
      },
    ],
    defaultDuration: 4,
  },
  {
    id: 'particle-burst',
    version: '1.0.0',
    params: [
      {
        name: 'count',
        label: 'Particles',
        type: 'number',
        min: 1,
        max: 300,
        step: 1,
        default: 90,
      },
      {
        name: 'speed',
        label: 'Speed',
        type: 'number',
        min: 0.05,
        max: 1,
        step: 0.01,
        default: 0.32,
      },
      {
        name: 'gravity',
        label: 'Gravity',
        type: 'number',
        min: -0.5,
        max: 1,
        step: 0.01,
        default: 0.16,
      },
      {
        name: 'life',
        label: 'Lifetime',
        type: 'number',
        min: 0.2,
        max: 8,
        step: 0.1,
        default: 3,
      },
      {
        name: 'radius',
        label: 'Particle size',
        type: 'number',
        min: 0.001,
        max: 0.03,
        step: 0.001,
        default: 0.007,
      },
      {
        name: 'color',
        label: 'Colour',
        type: 'color',
        default: '#e5b6ff',
      },
    ],
    defaultDuration: 4,
  },
  {
    id: 'data-pipeline',
    version: '1.0.0',
    params: [
      {
        name: 'nodes',
        label: 'Nodes',
        type: 'number',
        min: 2,
        max: 6,
        step: 1,
        default: 4,
      },
      {
        name: 'speed',
        label: 'Flow speed',
        type: 'number',
        min: 0.1,
        max: 3,
        step: 0.1,
        default: 1,
      },
      {
        name: 'labels',
        label: 'Node labels (comma separated)',
        type: 'text',
        default: 'INGEST,PROCESS,VERIFY,SHIP',
        maxLength: 150,
      },
      {
        name: 'color',
        label: 'Signal colour',
        type: 'color',
        default: '#82aaff',
      },
      {
        name: 'rate',
        label: 'Items per second',
        type: 'number',
        min: 1,
        max: 1000,
        step: 1,
        default: 42,
      },
    ],
    defaultDuration: 6,
  },
  {
    id: 'kinetic-letters',
    version: '1.0.0',
    params: [
      {
        name: 'text',
        label: 'Text',
        type: 'text',
        default: 'MAKE IT MOVE',
        maxLength: 40,
      },
      {
        name: 'stagger',
        label: 'Letter stagger',
        type: 'number',
        min: 0,
        max: 0.3,
        step: 0.01,
        default: 0.065,
      },
      {
        name: 'frequency',
        label: 'Spring frequency',
        type: 'number',
        min: 0.5,
        max: 6,
        step: 0.1,
        default: 2.4,
      },
      {
        name: 'damping',
        label: 'Damping',
        type: 'number',
        min: 0.1,
        max: 0.95,
        step: 0.01,
        default: 0.62,
      },
      {
        name: 'color',
        label: 'Colour',
        type: 'color',
        default: '#ffe29a',
      },
      {
        name: 'glow',
        label: 'Glow',
        type: 'bool',
        default: true,
      },
    ],
    defaultDuration: 4,
  },
] as const;
