import { getLanguage, translate } from '../i18n';
const en: Record<string, string> = {
  low: 'Low EQ (dB, 200 Hz)',
  mid: 'Mid EQ (dB, 1 kHz)',
  high: 'High EQ (dB, 4 kHz)',
  compressor: 'Compressor',
  threshold: 'Threshold (dB)',
  ratio: 'Ratio',
  attack: 'Attack (seconds)',
  release: 'Release (seconds)',
  target: 'Target LUFS',
  normalize: 'Measure and normalize',
  measuring: 'Measuring audio…',
  normalized:
    'Measured {lufs} LUFS; adjustment {gain} dB. Re-measure after edits.',
  limited:
    'Target limited by sample peaks or gain limit; no true-peak limiter.',
  stale: 'Project changed during analysis. Please try again.',
  title: 'Sound',
  empty: 'Select one audio or video clip.',
  gainDb: 'Gain (dB)',
  pan: 'Pan (-1 left, +1 right)',
  fadeIn: 'Fade in (seconds)',
  fadeOut: 'Fade out (seconds)',
  muted: 'Mute clip',
  reset: 'Reset audio',
  key: 'Set volume key at playhead',
  clearKeys: 'Clear volume keys',
  keys: 'Volume keys: {count}',
  edit: 'Edit clip audio',
  locked: 'This track is locked.',
  error: 'Audio setting failed: {error}',
};
const hi: Record<string, string> = {
  low: 'लो EQ (dB, 200 Hz)',
  mid: 'मिड EQ (dB, 1 kHz)',
  high: 'हाई EQ (dB, 4 kHz)',
  compressor: 'कम्प्रेसर',
  threshold: 'थ्रेशोल्ड (dB)',
  ratio: 'अनुपात',
  attack: 'अटैक (सेकंड)',
  release: 'रिलीज़ (सेकंड)',
  target: 'लक्ष्य LUFS',
  normalize: 'मापें और नॉर्मलाइज़ करें',
  measuring: 'ऑडियो मापा जा रहा है…',
  normalized: 'मापा {lufs} LUFS; बदलाव {gain} dB। संपादन के बाद फिर मापें।',
  limited:
    'सैंपल पीक या गेन सीमा के कारण लक्ष्य सीमित है; ट्रू-पीक लिमिटर नहीं है।',
  stale: 'विश्लेषण के दौरान प्रोजेक्ट बदला। फिर कोशिश करें।',
  title: 'ध्वनि',
  empty: 'एक ऑडियो या वीडियो क्लिप चुनें।',
  gainDb: 'गेन (dB)',
  pan: 'पैन (-1 बायाँ, +1 दायाँ)',
  fadeIn: 'फ़ेड इन (सेकंड)',
  fadeOut: 'फ़ेड आउट (सेकंड)',
  muted: 'क्लिप म्यूट करें',
  reset: 'ऑडियो रीसेट करें',
  key: 'प्लेहेड पर वॉल्यूम की जोड़ें',
  clearKeys: 'वॉल्यूम की हटाएँ',
  keys: 'वॉल्यूम की: {count}',
  edit: 'क्लिप ऑडियो बदलें',
  locked: 'यह ट्रैक लॉक है।',
  error: 'ऑडियो सेटिंग विफल: {error}',
};
export const soundText = (
  key: string,
  params?: Record<string, string | number>,
) => translate(key, params, getLanguage(), { en, hi });
